version: '3.8'

services:
  catalog:
    build: ./catalog
    ports:
      - "8001:8000"
  
  orders:
    build: ./orders
    ports:
      - "8002:8000"

  userservice:
    build: ./userservice
    ports:
      - "8003:8000" 
  
  gateway:
    build: ./gateway
    ports:
      - "8000:8000" 